"""empty message

Revision ID: 158efb26bb09
Revises: 7f183dd8376e
Create Date: 2020-05-11 17:36:52.661627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158efb26bb09'
down_revision = '7f183dd8376e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
